# Generated by Django 3.1.1 on 2022-12-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20221217_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GitDatabase',
            new_name='deliverydatabase',
        ),
    ]
