# Generated by Django 4.1.4 on 2022-12-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20221217_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydatabase',
            options={'permissions': (('view_status', 'can view staff details.'), ('view_customer_id', 'can view customer details'))},
        ),
    ]
